import { Inter } from "next/font/google";
import "./globals.css";
import {AuthContextProvider}  from "../../context/authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout =({ children }) => {
  return(
    <div className={"flex flex-col h-screen"}>
      { children }
      <Footer></Footer>
    </div>
  )
}

const Footer = () => {
  return (
    <footer className="bg-black-2 p-0 text-orange-500 font-light font-sm text-center">
      HCode122 - 2024 - All rights reserved
    </footer>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <MainLayout>
              {children}
              </MainLayout> 
        </AuthContextProvider>

      </body>
    </html>
  )
}