import { Inter } from "next/font/google";
import "./globals.css";
import {AuthContextProvider}  from "../../context/authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout =({ children }) => {
  return(
    <div className="bg-indigo-700">
      { children }
    </div>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <MainLayout>
              <main>{children}</main>
              </MainLayout> 
        </AuthContextProvider>

      </body>
    </html>
  )
}